### ISSUE TITLE
swagger UI not served at http://127.0.0.1:5665/__docs__/  after #* @assets ./static /

### ISSUE THREAD

**Issue by pcias** [rstudio/plumber#773] opened 2021-02-21 18:39 UTC
### System details

Output of `sessioninfo::session_info()()`:

```
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2021-02-21                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version date       lib source        
 assertthat             0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 cellranger             1.1.0   2016-07-27 [1] CRAN (R 4.0.2)
 cli                    2.2.0   2020-11-20 [1] CRAN (R 4.0.2)
 colorspace             2.0-0   2020-11-11 [1] CRAN (R 4.0.2)
 crayon                 1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 crosstalk              1.1.0.1 2020-03-13 [1] CRAN (R 4.0.2)
 curl                   4.3     2019-12-02 [1] CRAN (R 4.0.1)
 data.table           * 1.13.6  2020-12-30 [1] CRAN (R 4.0.3)
 DBI                    1.1.1   2021-01-15 [1] CRAN (R 4.0.2)
 digest                 0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
 dplyr                * 1.0.4   2021-02-02 [1] CRAN (R 4.0.2)
 ellipsis               0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 fansi                  0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
 forcats                0.5.0   2020-03-01 [1] CRAN (R 4.0.2)
 foreign                0.8-80  2020-05-24 [1] CRAN (R 4.0.3)
 generics               0.1.0   2020-10-31 [1] CRAN (R 4.0.2)
 ggplot2                3.3.3   2020-12-30 [1] CRAN (R 4.0.3)
 glue                   1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 gtable                 0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
 haven                  2.3.1   2020-06-01 [1] CRAN (R 4.0.2)
 hms                    0.5.3   2020-01-08 [1] CRAN (R 4.0.2)
 htmltools              0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
 htmlwidgets          * 1.5.3   2020-12-10 [1] CRAN (R 4.0.2)
 httpuv                 1.5.4   2020-06-06 [1] CRAN (R 4.0.2)
 httr                   1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
 jsonlite               1.7.2   2020-12-09 [1] CRAN (R 4.0.2)
 later                  1.1.0.1 2020-06-05 [1] CRAN (R 4.0.2)
 lattice                0.20-41 2020-04-02 [1] CRAN (R 4.0.3)
 lifecycle              0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
 lubridate            * 1.7.9.2 2020-11-13 [1] CRAN (R 4.0.2)
 magrittr               2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
 munsell                0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
 openxlsx               4.2.3   2020-10-27 [1] CRAN (R 4.0.2)
 PerformanceAnalytics * 2.0.4   2020-02-06 [1] CRAN (R 4.0.2)
 pillar                 1.4.7   2020-11-20 [1] CRAN (R 4.0.2)
 pkgconfig              2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
 plumber              * 1.0.0   2020-09-14 [1] CRAN (R 4.0.3)
 profvis                0.3.7   2020-11-02 [1] CRAN (R 4.0.2)
 promises               1.1.1   2020-06-09 [1] CRAN (R 4.0.2)
 purrr                  0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 quadprog               1.5-8   2019-11-20 [1] CRAN (R 4.0.2)
 Quandl                 2.10.0  2019-06-12 [1] CRAN (R 4.0.2)
 quantmod             * 0.4.18  2020-12-09 [1] CRAN (R 4.0.2)
 R6                     2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
 Rcpp                   1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
 reactable            * 0.2.3   2020-10-04 [1] CRAN (R 4.0.2)
 reactR                 0.4.3   2020-07-12 [1] CRAN (R 4.0.2)
 readxl                 1.3.1   2019-03-13 [1] CRAN (R 4.0.2)
 rio                  * 0.5.16  2018-11-26 [1] CRAN (R 4.0.2)
 rlang                  0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
 rnbp                 * 0.2.0   2020-06-29 [1] CRAN (R 4.0.2)
 rstudioapi             0.13    2020-11-12 [1] CRAN (R 4.0.2)
 scales                 1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
 sessioninfo            1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 stringi                1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
 stringr                1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
 svDialogs            * 1.0.0   2018-04-26 [1] CRAN (R 4.0.2)
 svGUI                  1.0.0   2018-04-23 [1] CRAN (R 4.0.2)
 swagger                3.33.1  2020-10-02 [1] CRAN (R 4.0.2)
 tibble                 3.0.4   2020-10-12 [1] CRAN (R 4.0.2)
 tidyquant            * 1.0.2   2020-10-21 [1] CRAN (R 4.0.2)
 tidyr                * 1.1.2   2020-08-27 [1] CRAN (R 4.0.2)
 tidyselect             1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
 tinytex                0.28    2020-12-14 [1] CRAN (R 4.0.2)
 triebeard              0.3.0   2016-08-04 [1] CRAN (R 4.0.2)
 TTR                  * 0.24.2  2020-09-01 [1] CRAN (R 4.0.2)
 urltools             * 1.7.3   2019-04-14 [1] CRAN (R 4.0.2)
 vctrs                  0.3.6   2020-12-17 [1] CRAN (R 4.0.2)
 webutils               1.1     2020-04-28 [1] CRAN (R 4.0.2)
 withr                  2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xfun                   0.19    2020-10-30 [1] CRAN (R 4.0.2)
 xts                  * 0.12.1  2020-09-09 [1] CRAN (R 4.0.2)
 yaml                   2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
 zip                    2.1.1   2020-08-27 [1] CRAN (R 4.0.2)
 zoo                  * 1.8-8   2020-05-02 [1] CRAN (R 4.0.2)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

### Example application *or* steps to reproduce the problem

```R
#* @assets ./static /
```

### Describe the problem in detail
After adding default routing to static html (for the purpose of self contained site with index.html, the endpoint of /__docs__/ does not work anymore. Other endpoint are ok

> plumb(file='plumber.R')$run()
Running plumber API at http://127.0.0.1:5665
Running swagger Docs at http://127.0.0.1:5665/__docs__/

**Comment by meztez** [comment] 2021-02-21 20:06
install from github, I believe this was already fixed.

**Comment by schloerke** [comment] 2021-03-01 22:54
This is recognized in https://github.com/rstudio/plumber/pull/748 and we hope to resolve it in https://github.com/rstudio/plumber/issues/749 in `v1.2.0`

**Comment by schloerke** [comment] 2021-03-01 22:55
Thank you for posting a great reprex! Closing as duplicate of core issue of #749

**Closed by schloerke** 2021-03-01 22:55 UTC

**Comment by vspinu** [comment] 2021-05-05 08:50
@schloerke how to disable swagger altogether? Or at least the message `Running swagger Docs at ...` in the terminal?

**Comment by schloerke** [comment] 2021-05-05 14:21
@vspinu Please open a new issue if it is unrelated to one you are posting on.

I've made an issue on your behalf: https://github.com/rstudio/plumber/issues/801
