### ISSUE TITLE
pkgdown site font rendering

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#853] opened 2022-03-23 22:42 UTC
The [pkgdown site](https://www.rplumber.io/) seems to be rendering fonts incorrectly:

![image](https://user-images.githubusercontent.com/10444878/159808151-c70cc390-1121-42ff-9e5b-57e306772233.png)

**Comment by meztez** [comment] 2022-03-23 23:21
I get Liberation Serif like @blairj09.

Seems to be missing link in the<head> section?
```html
<link href="deps/_Source%20Sans%20Pro-0.4.0/font.css" rel="stylesheet"><link href="deps/_Source%20Code%20Pro-0.4.0/font.css" rel="stylesheet">
```

**Comment by schloerke** [comment] 2022-03-24 16:28
I can see that the headdeps were not being passed to the template.

I can not reprex locally when rebuilding. It's been a month, so trying to build again from https://github.com/rstudio/plumber/commit/f444cfd7dd2cb0235fee5bb731ab4054c8637063.

Once GHA is back up, this should be fixed

**Comment by schloerke** [comment] 2022-03-24 17:21
It was committed and is there in the code.

--------------------------

It was there in the code before! 
Source: https://github.com/rstudio/plumber/blame/b2c7f5224d39818e24935c80c84264e666daec31/index.html#L21
Points to: https://github.com/rstudio/plumber/blob/b2c7f5224d39818e24935c80c84264e666daec31/deps/_Source%20Code%20Pro-0.4.0/font.css

Now:
Source: https://github.com/rstudio/plumber/blame/1b648e4402d5ec40555708ad22b34eca2ff0d0f8/index.html#L21
Points to: https://github.com/rstudio/plumber/blob/gh-pages/deps/_Source%20Code%20Pro-0.4.1/font.css

----------------------------------------------------
----------------------------------------------------

So at least we should see two requests to `font.css` and I don't see them from the site or the source of the site!!!

-----------------------

![Screen Shot 2022-03-24 at 1 16 26 PM](https://user-images.githubusercontent.com/93231/159973363-a4e6a382-c093-417d-844a-088328ee39c8.png)

Where are all of these cloudfront locations coming from? I believe to have a custom url, you must register your DNS with cloudfront ... is cloudfront messing with the source content?!? 

**confused-jackie-chan.png . Why would they do this? Why do some links work and not others? I wonder if the `%20` in the path is throwing them off.

**Comment by schloerke** [comment] 2022-03-24 17:30
@trestletech Is there a setting in our DNS that is altering the paths for static files?

I can not reproduce this cloudfront behavior with `{shinytest2}` at https://rstudio.github.io/shinytest2/ . All css files are loading as expected for `{shinytest2}`.

Do we need a custom DNS setting? Can we just have GitHub be the host? The only thing we'd drop is support for is netlify redirects that are a few years old by now.

**Comment by trestletech** [comment] 2022-03-24 17:44
Hm... I'd be suspicious of some Netlify cleverness. I'm not aware of any boutique DNS settings on that domain. I know Netlify has some "do some magic for me" buttons that perhaps we need to disable? They might be accelerating things via CloudFront on our behalf.

**Comment by meztez** [comment] 2022-03-24 18:47
Can you clear the cached files for this website? It might be still serving the cached version.

**Comment by schloerke** [comment] 2022-03-24 18:58
@trestletech Could you check for me? I do not have access to our Netlify. Thank you!

**Comment by trestletech** [comment] 2022-03-24 19:07
Sadly I think I was removed from our Netlify account a few months back. IT Helpdesk? :/ Sorry about that

**Comment by schloerke** [comment] 2022-03-24 19:18
Netlify was being tricksy and trying to bundle CSS and JS into a single file. 👎 

Fixed in the Netlify settings.

**Closed by schloerke** 2022-03-24 19:18 UTC
