### ISSUE TITLE
Help understanding problem rendering pdf with plumber

### ISSUE THREAD

**Issue by HPicatto** [rstudio/plumber#857] opened 2022-04-25 01:47 UTC
Hello, I posted a problem that I'm having 10 days ago on the Rstudio community but I didn't get any help. https://community.rstudio.com/t/help-understanding-problem-rendering-pdf-with-plumber/134266?u=hpicatto

I'm having problems understanding what I'm doing wrong when serializing a report using plumber
```

#* produce the report
#* @param userID:str userID
#* @param title:str title of repot
#* @param taskId:str id of the task
#* @param alpha:double confidence interval for plots
#* @serializer contentType list(type = "application/pdf")
#* @get /pdf

function(userID = "realUser1", 
         title = "Draft Report task1",
         taskId = "realRask1",
         alpha = 0.1){
  tmp <- tempfile()
  name = paste0(tmp,'.pdf')
  res$setHeader("Content-Disposition", paste0("attachment; filename=", basename(name)))
  rmarkdown::render(input = "~/BiologyAPP/BiologyAPI/BiologicalDataAPI/reports/testReport.Rmd", 
                    output_file= tmp,
                    params = list(author= userID,
                                  title= title,
                                  date= Sys.Date(),
                                  taskId= taskId,
                                  alpha= alpha))
  on.exit({file.remove(name)}, add = TRUE)
  readBin(name, "raw", n=file.info(name)$size)
}
```
for some reason I can't run the code if I use the tag serializer. it returns:

> 
> Running plumber API at http://127.0.0.1:9064/
> Error in nchar(ctype) :
> cannot coerce type 'closure' to vector of type 'character'

but the same error disappears if I remove the tag, of course that then I've problems on the other end for deserializing an unknown file

My R session result is:
> sessionInfo()
> R version 4.1.2 (2021-11-01)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS:   /usr/local/R/lib64/R/lib/libRblas.so
> LAPACK: /usr/local/R/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] textutils_0.2-1             shiny_1.7.1                 pdftools_3.1.1              tinytex_0.37               
>  [5] ShortRead_1.52.0            GenomicAlignments_1.30.0    BiocParallel_1.28.3         Rsubread_2.8.2             
>  [9] future_1.24.0               snpStats_1.44.0             survival_3.2-13             VariantAnnotation_1.40.0   
> [13] SummarizedExperiment_1.24.0 Biobase_2.54.0              MatrixGenerics_1.6.0        matrixStats_0.61.0         
> [17] Rsamtools_2.10.0            Biostrings_2.62.0           XVector_0.34.0              GenomicRanges_1.46.1       
> [21] GenomeInfoDb_1.30.1         IRanges_2.28.0              S4Vectors_0.32.3            BiocGenerics_0.40.0        
> [25] plumber_1.1.0               gtsummary_1.5.2             here_1.0.1                  httr_1.4.2                 
> [29] PKI_0.1-11                  base64enc_0.1-3             yaml_2.3.5                  lmerTest_3.1-3             
> [33] markdown_1.1                BGLR_1.0.9                  jsonlite_1.8.0              mongolite_2.5.0            
> [37] snpReady_0.9.6              impute_1.68.0               rgl_0.108.3                 matrixcalc_1.0-5           
> [41] properties_0.0-9            lme4GS_0.1                  lme4_1.1-28                 Matrix_1.3-4               
> [45] rJava_1.0-6                 adegenet_2.1.5              ade4_1.7-18                 AGHmatrix_2.0.4            
> [49] vcfR_1.12.0                 promises_1.2.0.1            forcats_0.5.1               stringr_1.4.0              
> [53] purrr_0.3.4                 readr_2.1.2                 tidyr_1.2.0                 tibble_3.1.6               
> [57] ggplot2_3.3.5               tidyverse_1.3.1             BiocManager_1.30.16         dplyr_1.0.8                
> [61] RCurl_1.98-1.6              kableExtra_1.3.4           
> 
> loaded via a namespace (and not attached):
>   [1] utf8_1.2.2             tidyselect_1.1.2       RSQLite_2.2.11         AnnotationDbi_1.56.2   htmlwidgets_1.5.4     
>   [6] grid_4.1.2             munsell_0.5.0          codetools_0.2-18       withr_2.5.0            colorspace_2.0-3      
>  [11] filelock_1.0.2         highr_0.9              knitr_1.37             rstudioapi_0.13        listenv_0.8.0         
>  [16] labeling_0.4.2         GenomeInfoDbData_1.2.7 hwriter_1.3.2          farver_2.1.0           bit64_4.0.5           
>  [21] rprojroot_2.0.2        parallelly_1.30.0      vctrs_0.3.8            generics_0.1.2         xfun_0.30             
>  [26] BiocFileCache_2.2.1    qpdf_1.1               R6_2.5.1               bitops_1.0-7           cachem_1.0.6          
>  [31] webutils_1.1           DelayedArray_0.20.0    assertthat_0.2.1       BiocIO_1.4.0           scales_1.1.1          
>  [36] pinfsc50_1.2.0         gtable_0.3.0           globals_0.14.0         rlang_1.0.2            systemfonts_1.0.4     
>  [41] splines_4.1.2          rtracklayer_1.54.0     broom_0.7.12           reshape2_1.4.4         modelr_0.1.8          
>  [46] GenomicFeatures_1.46.5 backports_1.4.1        httpuv_1.6.5           tools_4.1.2            ellipsis_0.3.2        
>  [51] jquerylib_0.1.4        RColorBrewer_1.1-2     Rcpp_1.0.8.3           plyr_1.8.6             progress_1.2.2        
>  [56] zlibbioc_1.40.0        prettyunits_1.1.1      openssl_2.0.0          fontawesome_0.2.2      zoo_1.8-9             
>  [61] swagger_3.33.1         haven_2.4.3            cluster_2.1.2          fs_1.5.2               magrittr_2.0.2        
>  [66] reprex_2.0.1           truncnorm_1.0-8        hms_1.1.1              mime_0.12              evaluate_0.15         
>  [71] xtable_1.8-4           XML_3.99-0.9           jpeg_0.1-9             readxl_1.3.1           compiler_4.1.2        
>  [76] biomaRt_2.50.3         gt_0.4.0               crayon_1.5.0           minqa_1.2.4            htmltools_0.5.2       
>  [81] mgcv_1.8-38            later_1.3.0            tzdb_0.2.0             lubridate_1.8.0        DBI_1.1.2             
>  [86] dbplyr_2.1.1           MASS_7.3-54            broom.helpers_1.6.0    rappdirs_0.3.3         boot_1.3-28           
>  [91] permute_0.9-7          cli_3.2.0              igraph_1.2.11          pkgconfig_2.0.3        numDeriv_2016.8-1.1   
>  [96] xml2_1.3.3             svglite_2.1.0          bslib_0.3.1            webshot_0.5.2          rvest_1.0.2           
> [101] digest_0.6.29          vegan_2.5-7            rmarkdown_2.13         cellranger_1.1.0       restfulr_0.0.13       
> [106] curl_4.3.2             rjson_0.2.21           nloptr_1.2.2.3         lifecycle_1.0.1        nlme_3.1-153          
> [111] seqinr_4.2-8           askpass_1.1            viridisLite_0.4.0      BSgenome_1.62.0        fansi_1.0.2           
> [116] pillar_1.7.0           lattice_0.20-45        KEGGREST_1.34.0        fastmap_1.1.0          glue_1.6.2            
> [121] png_0.1-7              bit_4.0.4              sass_0.4.0             stringi_1.7.6          blob_1.2.2            
> [126] latticeExtra_0.6-29    memoise_2.0.1          ape_5.6-2

**Comment by schloerke** [comment] 2022-04-25 14:54
Hmmm. This points to a bug in https://github.com/rstudio/plumber/blob/06e46f3ff5119e5f1cb8af29ef49aecb3cbb932a/R/openapi-spec.R#L64-L74

Thank you for the endpoint code!

**Comment by HPicatto** [comment] 2022-04-26 06:58
pardon me if english eludes me as I'm not a native speaker, but I don't see how to solve the problem. It is just a bug and I have to deal with it in my own way?

**Comment by meztez** [comment] 2022-04-27 13:22
@HPicatto, I am not able to reproduce the problem on Ubuntu Linux or Windows, for 4.1.3 and plumber 1.1. If I run the code provided, it does not behave like you mentioned. Any other particularity to the environment you execute this in?

**Comment by rfineman** [comment] 2022-04-27 17:16
I have been running into the same issue. Issue arises when using the user-defined serializer tag "contentType". 

For example, this [code](https://github.com/rstudio/plumber/blob/06e46f3ff5119e5f1cb8af29ef49aecb3cbb932a/tests/testthat/files/content-type.R) will work:
```
#* @serializer text
#* @get /
function(){
  "RESULT"
}
```

However, this code will return the error:
```
#* @serializer contentType list(type="text/plain")
#* @get /
function(){
  "RESULT"
}
```

> Error in nchar(ctype) : 
>   cannot coerce type 'closure' to vector of type 'character'

**Comment by meztez** [comment] 2022-04-27 17:38
I still cannot reproduce it. Really confusing.
![ctype_plumber_wtf](https://user-images.githubusercontent.com/31039074/165586416-b98536b8-8383-42b2-80ed-7e9fc8e50f5e.gif)

**Comment by meztez** [comment] 2022-04-27 18:27
@rfineman I've got it

**Comment by meztez** [comment] 2022-04-27 18:40
@rfineman , @HPicatto . This was fixed in https://github.com/rstudio/plumber/commit/3d0c4ae8b62a62b5bb6b363a83e8f52889c72a2e.

Issue is `get("type", envir = environment(get("serialize_fn", envir = environment(endpts$serializer))))` returns `arrow::type` function.

But this has not been released to CRAN yet. You can use the github version.

**Comment by schloerke** [comment] 2022-04-27 18:43
Thank you for the debugging, @meztez !

We should have a release for plumber out in the next two weeks. I presented on `shinytest2` today, so I am going to shift focus to release webshot2 and plumber.

**Comment by schloerke** [comment] 2022-06-02 20:39
Closing via https://github.com/rstudio/plumber/issues/857#issuecomment-1111354217

**Closed by schloerke** 2022-06-02 20:39 UTC
