### ISSUE TITLE
Why plumber launches multiple processes?

### ISSUE THREAD

**Issue by david-cortes** [rstudio/plumber#494] opened 2019-10-02 12:49 UTC
I notice in the documentation it's explicitly stated that plumber is single-threaded due to R limitations, but when I launch some plumber service, I notice it spawns 2 processes, and after sending a couple requests it might have 3-4 processes running. Using `prlimit` to limit it to 2 processes will not spawn any more processes, and things seem to work just fine with only the initial 2.

What are these additional processes for?

**Comment by schloerke** [comment] 2019-10-02 13:53
Where is the plumber API being hosted?

**Comment by david-cortes** [comment] 2019-10-02 14:05
It's hosted on a regular AWS server and launched with `Rscript`. Also see multiple processes when launching and using it on my local machine.

**Comment by schloerke** [comment] 2019-10-02 14:10
plumber is not doing any process launching or handling.  I do not know how multiple R processes are running as a result of calling `pr$run()`. 😕 

How is your routing handled? Are you launching a new plumber process for each route?

**Comment by david-cortes** [comment] 2019-10-02 14:18
I don't think it's launching a separate process for each route because everything is under the default settings - basically I just have a file like this:
```r
library(plumber)
r <- plumb("file.R")
r$run(host = host, port = port)
```

Which I launch with `Rscript plumber_file.R`, and the routes are all decorated like this:
```r
### Internal name ----
#* bla bla bla
#* @param req Request JSON
#* @serializer unboxedJSON
#* @get /this_path
#* @post /this_path
```

The functions themselves are not doing anything like `makePSOCKcluster`, and after several hundred calls it's still 3-4 processes, which are not zombie process.

**Comment by schloerke** [comment] 2019-10-03 15:44
I promise plumber is not doing anything with processes.  In the github version, we are now allowing for async/future values, but unless you specifically ask for extra processes, the extra R processes should never be generated.

I could image maybe your R code is calling extra R cores, but this does not seem to be the case. 🤷‍♂ 


------------------------

I am going to close this issue as I can't reproduce this situation and is outside of the plumber scope.

If you solve the issue, please followup on this issue! Thank you

**Closed by schloerke** 2019-10-03 15:44 UTC

**Comment by wch** [comment] 2019-10-03 21:13
Running an httpuv application will cause two threads to start: one from httpuv itself, and one that is started by the `later` package. They are threads within the same process. Perhaps the program you're using to find out about processes is also showing individual threads?

**Comment by david-cortes** [comment] 2019-10-04 08:18
Yes, the software I'm using (top/htop) shows individual threads.
