### ISSUE TITLE
Plumber $run method needs documentation

### ISSUE THREAD

**Issue by rafamerlin** [rstudio/plumber#449] opened 2019-06-11 01:31 UTC
Hi, I'm using the latest plumber docker image and trying to run a very simple script.

This is my dockerfile:

```
FROM trestletech/plumber

WORKDIR /app/

COPY . .

CMD ["/app/test.R"]
```

This is my test.R file:
```
#' @get /simple
function(){
  stop("I'm an error!")
}

#' @get /healthCheck
function(){
    list(200, "Health Check passed", Sys.getenv("hostname"))
}
```

Healthcheck returns a 200 and this:

```
[
    [
        200
    ],
    [
        "Health Check passed"
    ],
    [
        ""
    ]
]
```

However, if I call the error one, instead of returning the message as the documentation says it does, it just returns a 500 and this:

```
{
    "error": [
        "500 - Internal server error"
    ]
}
```

Am I missing some config or something? Maybe :latest is not the right tag for the docker image? 

Ah, this is the plumber console:

```
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=8000)
Starting server to listen on port 8000
Warning in if (stri_startswith_fixed(body, "{")) { :
  the condition has length > 1 and only the first element will be used
<simpleError in (function () {    stop("I'm an error!")})(): I'm an error!>
```

**Comment by schloerke** [comment] 2019-06-11 12:36
Correct.  There should be a `message` key in the error object.  It should be returning :

```
{
  "error": [ "500 - Internal server error" ],
  "message": "I'm an error"
}
```

If you run it in the console (not in docker), can you get the error message?  If I copy your code and run the API, I can not reproduce it with CRAN or GitHub master branch.

This is odd.

**Comment by Merurino** [comment] 2019-06-12 03:06
Hey @schloerke,

Installed plumber from Cran, and ran it like this:

Plumber.R
```
#' @get /simple
function(){
  stop("I'm an error!")
}

#' @get /healthCheck
function(){
  list(200, "Health Check passed", Sys.getenv("hostname"))
}
```

Saved it and ran in R Studio this code:

```
library(plumber)
r <- plumb("plumber.R")  # Where 'plumber.R' is the location of the file shown above
r$run(port=8000)
```

One thing I saw immediately is that the CRAN version runs swagger UI when running plumber. If I try /__swagger__/ in the one running on docker it will return me this:

`{"error":["404 - Resource Not Found"]}`

Also, when running the query for the error, it does return the message properly:

```
{
    "error": [
        "500 - Internal server error"
    ],
    "message": [
        "Error in (function () : I'm an error!\n"
    ]
}
```

I'm wondering why that would happen though, is there a possibility that the docker images on dockerhub are outdated? Maybe the latest tag is not the proper one. Maybe it's just missing some configuration that is automatically disabled for the docker images?

**Comment by schloerke** [comment] 2019-06-12 13:07
When running in Docker, set `r$run(port = 8000, swagger = TRUE)`.  By default `swagger` is set to `interactive()`, which is `FALSE` in a Docker script.

**Comment by Merurino** [comment] 2019-06-13 00:20
Do you think that could be related to the error message not coming from the docker? Were you able to test it on docker?

If you want I can try to create a project with it working so you can just clone and run to test it.

**Comment by Merurino** [comment] 2019-06-18 07:30
Hello again. 

I managed to figure out why it wasn't printing the message. It was the debug interactive (your tip about swagger helped me to find it).

If you're not running plumber with Debug it will not print the message out for you. There's even a test for it: https://github.com/trestletech/plumber/blob/095b5377812d60664e6cc955b1417c4cf46d44c2/tests/testthat/test-default-handlers.R#L28

I've created my own docker image and added the debug option and now I get the error messages. I am not sure where to edit the docs from rplumber.io but maybe it would be useful to mention that there. 

Thanks again for all the help.

**Comment by Merurino** [comment] 2019-07-16 00:57
So, I've just found out that if I add a serializer to the method it will also not return the reason for stopping.

So, by adding this to my method I will not get the error back any more.
```
#' @serializer contentType list(type="application/json")
```

**Comment by schloerke** [comment] 2020-07-09 15:12
R6 docs added in https://github.com/rstudio/plumber/pull/530. Closing

**Closed by schloerke** 2020-07-09 15:12 UTC
Labels: docs
