### ISSUE TITLE
Bypassing serialization example fails with current GH build

### ISSUE THREAD

**Issue by blairj09** [rstudio/plumber#597] opened 2020-07-17 21:16 UTC
The [bypassing serialization example](https://www.rplumber.io/articles/rendering-output.html#bypassing-serialization) returns a 500 error on the current GH build of the package. The same error doesn't occur with the CRAN release.

```r
#* Endpoint that bypasses serialization
#* @get /foo
function(res){
  res$body <- "Literal text here!"
  
  res
}
```

![image](https://user-images.githubusercontent.com/10444878/87831302-61a6b980-c840-11ea-9303-13895e0298c0.png)

**Comment by schloerke** [comment] 2020-07-20 18:28
I believe this is related / the root cause: https://github.com/rstudio/httpuv/issues/195

**Comment by schloerke** [comment] 2020-09-23 20:50
Closing as this issue should be fixed by httpuv

**Closed by schloerke** 2020-09-23 20:50 UTC
Labels: out of focus
